# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170325_0114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report_Subject',
            new_name='Subject',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_subject',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_title',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
