# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_report_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_text',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='report',
            name='conclusion',
        ),
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Report_Text',
        ),
    ]
