# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(),
        ),
    ]
